config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/import'

  resources :files do
    collection { post :import }
  end

  get 'internal' , to: 'files#index'

  root to: "files#index"

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/row.rb
class Row
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :data, type: Mongoid::EncryptedString
  validates_uniqueness_of :data, case_sensitive: true # Works as expected

  scope :failed, ->{ where(:_failed.exists =>true) }

  belongs_to :uploadedCsvFile
end

app/models/uploaded_csv_file.rb
class UploadedCsvFile
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::DateHelper


  field :file, type: String
  field :batch_id, type: String
  field :type, type: String

  belongs_to :user
  has_many :rows, dependent: :delete

  mount_uploader :file, CsvFileUploader

  def on_complete(status, options)
    puts "complete"
    this_file = UploadedCsvFile.find(options['uid'])
    UserNotifier.send_job_done_email(this_file).deliver_now
    this_file.user.destroy
  end

  def self.import(file, domain, username, password, filetype, token, token_secret, consumer_key, consumer_secret, auth_type)

    Redis.new.ping


    usr = User.create(
      :username => username,
      :domain => domain,
      :password => password,
      :token => token,
      :token_secret => token_secret,
      :consumer_key => consumer_key,
      :consumer_secret => consumer_secret,
      :auth_type => auth_type
    )
    u = UploadedCsvFile.create(:file => file, :type => filetype)
    usr.uploadedCsvFiles.push(u)

    ProcessInboundCSVFile.perform_async(u.id.to_s)
  end


end

app/models/user.rb
class User
  include Mongoid::Document

  field :auth_type, type: String
  field :username, type: Mongoid::EncryptedString
  field :password, type: Mongoid::EncryptedString

  field :token, type: Mongoid::EncryptedString
  field :token_secret, type: Mongoid::EncryptedString
  field :consumer_key, type: Mongoid::EncryptedString
  field :consumer_secret, type: Mongoid::EncryptedString

  field :domain, type: Mongoid::EncryptedString


  has_many :uploadedCsvFiles, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    #@customers = Customer.all
  end

  def import
    num_imported = Customer.import(params[:file], params[:domain], params[:username], params[:password])
    redirect_to root_url, notice: "CSV queued and is uploading in the background.  You will receive an email when finished."
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
    Redis.new.ping

    #@customers = Customer.all
  end

  def import
    Redis.new.ping

    num_imported = UploadedCsvFile.import(
      params[:file],
      params[:domain],
      params[:username],
      params[:password],
      params[:filetype],
      params[:token],
      params[:token_secret],
      params[:consumer_key],
      params[:consumer_secret],
      params[:auth_type]

    )
    redirect_to root_url, notice: "CSV queued and is uploading in the background.  You will receive an email when finished."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/files/import.html.erb
<h1>Customers#import</h1>
<p>Find me in app/views/files/import.html.erb</p>

app/views/files/index.html.erb
 <!-- SUCCESS BOX -->
<% if flash[:notice] -%>
  <div class="warning-box" style="background: #b7f597;">
    <h3 style="background: #2ac72f;">
      <span class="fa-stack fa-lg">
        <i class="fa fa-check-circle fa-stack-1x "></i>
      </span>
      Pending Import
  </h3>
    <div class="warning-content">
      <ul>
        <li><i class="fa-li fa fa-check"></i><%= flash[:notice] %></li>
      </ul>
    </div>
  </div>
<% end %>
<!-- <h4>Import CSV File</h4> -->
<%= form_tag import_files_path, multipart: true do %>
  <h3>Authentication Type</h3>
  <p>
    <%= radio_button_tag :auth_type, 'password',  false, :required => true, :checked => true%>
    <label for="">Password Auth</label>
    <br />
    <%= radio_button_tag :auth_type, 'API',  false, :required => true %>
    <label for="">API Auth</label>
  </p>
  <p>
    <%= label_tag(:username, "Username", id: 'username_label') %>
    <%= text_field_tag :username,nil, :required => true %>
  </p>
  <div id="pw_fields">
    <%= label_tag(:password, "Password") %>
    <%= password_field_tag :password,nil, :required => true %>
  </div>
  <div id="api_fields">
    <p>
      <%= label_tag(:token, "Token") %>
      <%= text_field_tag :token,nil, :required => true %>
    </p>
    <p>
      <%= label_tag(:token_secret, "Token Secret") %>
      <%= password_field_tag :token_secret,nil, :required => true %>
    </p>
    <p>
      <%= label_tag(:consumer_key, "Consumer Key") %>
      <%= text_field_tag :consumer_key,nil, :required => true %>
      <p>
        <%= label_tag(:consumer_secret, "Consumer Secret") %>
        <%= password_field_tag :consumer_secret,nil, :required => true %>
      </p>
    </div>
    <%= label_tag(:domain, "Domain") %>
    <%= text_field_tag :domain,nil, :required => true, :placeholder => "domain.desk.com" %>
    <div class="warning-box" style="margin-bottom: 15px;">
      <h3>
        <span class="fa-stack fa-lg">
          <i class="fa fa-exclamation-triangle fa-stack-1x "></i>
        </span>
        Important Information
    </h3>
      <div class="warning-content">
        <ul class="fa-ul">
          <li><i class="fa-li fa fa-exclamation"></i>Before uploading, please check that your CSV files are in this <a href="https://github.com/desklabs/desk-uploader/blob/master/CSV_Spec.md">format</a>.</li>
        </ul>
      </div>
    </div>
    <%= label_tag(:file, "CSV File") %>
    <%= file_field_tag :file, :required => true %><br/>
    <h3>File Type</h3>
    <p>
      <%= radio_button_tag :filetype, 'customer',  false, :required => true %>
      <label for="">Customer</label>
      <br />
      <%= radio_button_tag :filetype, 'company',  false, :required => true %>
      <label for="">Company</label>
    </p>
    <div class="form-button">
      <%= submit_tag "Import CSV", :id => 'submit'%>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  jQuery(document).ready(function ()
                                        {
                                          usePW();
                                            $("input[name=auth_type]").change(radioValueChanged);
                                        })
  
                                        function usePW()
                                        {
                                              $('#username_label').text("Username")
  
                                              $('#username').val('');
                                              $('#password').val('');
                                              $('#token').val('n/a');
                                              $('#token_secret').val('n/a');
                                              $('#consumer_key').val('n/a');
                                              $('#consumer_secret').val('n/a');
                                                $('#pw_fields').slideDown();
                                                $('#api_fields').slideUp();
                                        }
  
                                        function useAPI()
                                        {
                                              //$('#username').val('n/a');
                                              $('#username_label').text("Your Email")
  
                                              $('#password').val('n/a');
                                              $('#token').val('');
                                              $('#token_secret').val('');
                                              $('#consumer_key').val('');
                                              $('#consumer_secret').val('');
                                                $('#pw_fields').slideUp();
                                                $('#api_fields').slideDown();
                                        }
                                        function radioValueChanged()
                                        {
                                            radioValue = $(this).val();
  
                                            console.log(radioValue);
  
                                            if($(this).is(":checked") && radioValue == "API")
                                            {
                                              useAPI();
                                            }
                                            else
                                            {
                                              usePW();
  
                                            }
                                        }
</script>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="muted credit"><a href="https://github.com/desklabs/desk-uploader/issues">Please report issues/bugs here.</a></p>
    <p class="muted credit">Version: <%= require 'version'; Version.current %></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to "Desk.com CSV Uploader", root_path, class: "navbar-brand" %>
  <!--   <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Customers <span class="sr-only">(current)</span></a>
    </li>
  </ul> -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>CSV Uploader - Desk.com Toolbox </title>
    <!-- DESK ICON -->
    <link rel="icon" type="image/vnd.microsoft.icon" href="https://cdn.desk.com/assets/favicon-6996d629d8eda6554da097789a549459.ico">
    <link rel="icon" type="image/png" href="https://cdn.desk.com/assets/favicon-e35d809f46f88708acdeb9c8408472ff.png">
    <!-- LOAD IN NORMALIZE CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <!-- LOAD IN FONT -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700" rel="stylesheet">
    <!-- TOOLBOX MASTER CSS -->
    <link rel="stylesheet" href="https://s3.amazonaws.com/desk-wow/toolbox/tool.css">
    <!-- LOAD IN ICONS -->
    <script src="https://use.fontawesome.com/13b411ba91.js"></script>
    <!-- LOAD IN APPLICATION JS -->
    <%= javascript_include_tag "application" %>
    <style>
      /* MOVE TO MASTER CSS */
      
#footer {
    position: absolute;
    right: 0px;
    text-align: right;
}

          input[type="radio"] {
            width: 20px;
          }
      
          input[type="file"] {
            margin: 0;
            padding: 0;
            border: none;
            padding-top: 0;
            margin-top: 15px;
            padding-bottom: 30px;
            margin-bottom: 30px;
          }
      
        input[type="radio"] + label {
            color:#3e3e3e;
            font-weight: 200;
        }
      
        input[type="radio"] + label span {
            display:inline-block;
            width:19px;
            height:19px;
            margin:-2px 10px 0 0;
            vertical-align:middle;
            background:url('https://s3.amazonaws.com/desk-wow/toolbox/check_radio_sheet.png') left top no-repeat;
            cursor:pointer;
        }
      
        input[type="radio"]:checked + label span {
            background:url('https://s3.amazonaws.com/desk-wow/toolbox/check_radio_sheet.png') -19px top no-repeat;
        }
    </style>
  </head>
  <body>
    <!-- SIDEBAR STARTS -->
    <div class="left">
      <!-- JS BUNDLE LOADS LAUNCHBAR HERE -->
    </div>
    <!-- SIDEBAR ENDS -->
    <!-- RIGHT SIDE CONTENT -->
    <div class="right">
      <!-- CONTENT SECTION HEADER -->
      <div class="header">
        <div class="app-logo"></div>
        <h1>
          <!-- SET PAGE HEADING ICON -->
          <span class="fa-stack fa-lg green">
            <i class="fa fa-upload fa-stack-1x "></i>
          </span>
          <!-- SET PAGE HEADING TEXT -->
          CSV Uploader
      </h1>
      </div>
      <!-- CONTENT SECTION HEADER END -->
      <!-- MAIN BODY CONTENT -->
      <div class="main">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
      <!-- MAIN BODY CONTENT END -->
    </div>
    <!-- RIGHT SIDE CONTENT END -->
    <!-- FOOTER JS SCRIPTS -->
    <!-- LOAD IN JQUERY -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <!-- LOAD IN LAUNCHBAR JS -->
    <script src='https://desk-toolbox.herokuapp.com/sidebar.js'></script>
    <!-- LOAD IN CUSTOM JS -->
    <!-- FOOTER JS END -->

  </body>
</html>
<script type="text/javascript">
  $( document ).ready(function() {
      $('div.left ul').hide();
  
            if (location.pathname.includes("internal") == true) {
                 $('div.left ul').show();
            }
          });
</script>

app/views/user_notifier/send_job_done_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Import Complete, <%= @user.username %>!</p>
    <p>It took <%= @elapsed_time%> to process <%= @total_rows%> rows.</p>
    <p><%= @failed_rows.count%> rows failed.</p>
  </body>
</html>

app/views/user_notifier/send_job_done_email_failures.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Import Complete, <%= @user.username %>!</p>
    <p>It took <%= @elapsed_time%> to process <%= @total_rows%> rows.</p>
    <p><%= @failed_rows.count%> rows failed.</p>
  </body>
</html>

app/views/user_notifier/send_job_done_email_no_failures.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Import Complete, <%= @user.username %>!</p>
    <p>It took <%= @elapsed_time%> to process <%= @total_rows%> rows.</p>
  </body>
</html>